# this file is basically from chibicc(https://github.com/rui314/chibicc)
#!/bin/bash
afterexit() {
    rm -f tmp tmp.s
    exit
}
assert() {
    expected="$1"
    input="$2"
    ./build/wizardc "$input" 2 > tmp.s || afterexit
    gcc -static -o tmp tmp.s
    ./tmp
    actual="$?"


    if [ "$actual" = "$expected" ]; then
        echo "$input => $actual OK" 
    else 
        echo "$input => $expected expected ,but got $actual"  
        afterexit
    fi
}

assert 0 "int main(){ return 0;}"
assert 255 "int main(){ return -1;}"
assert 5 "int main() { return (3+2*2)-2;}"
assert 7 "int main() { return ((-1*2+8)/2+4);}"
assert 17 "int main() { return 0x1 + 0x10;}"
assert 19 "int main() { return (0x1*0x10 + 0x3);}"
assert 1 "int main() { return 1 > 0; }"
assert 1 "int main() { return 0 < 1;}"
assert 1 "int main() { return 10 >= (1+1);}"
assert 1 "int main() { return 1 <= 2; }"
assert 1 "int main() { return -1 == 0-1; }"
assert 1 "int main() { return 1 != 2; }"
assert 11 "int main() { return 10+1; }"
assert 16 "int main() { return 15+1; }"
assert 11 "int main() { if(1>0) return 11; }"
assert 12 "int main() { if(1>0) return 12; else return 11; }"
assert 12 "int main() { if(1==0) {return 1+10;} else {return 1+11;} }"
assert 1 "int main() { if(1>0) if(0<2) return 1; else {return 11;} }"
assert 11 "int main() { if(1>0) if(0>2) return 1; else {return 11;} }"
assert 1 "int main() { if(1>0) { if(0<2) return 1;} else {return 11;} }"
assert 3 "int main() { if(1>0) { if(0>2) return 1; else return 3;} else {return 11;}}"
assert 3 "int main() {int a = 0;return a+3;}"
assert 14 "int main() {int a=11;return a+3; }"
assert 12 "int main() {int a=5,b=7;return a+b;}"
assert 5 "int main() {int a=5,b=a;return b;}"
assert 3 "int main() {int a=1,b=2;if(a<b) return a+b;else return a-b;}"
assert 7 "int ret3() { return 3;} int main(){ return ret3() + 4; }"
assert 8 "int ret5() { return 5;}int main(){ return ret5() + 3; }"
assert 5 "int addx(int a,int b) { return a+b;} int main(){ return addx(3,2); }"
assert 6 "int ret3(){return 3;} int addx(int a,int b) { return a+b;} int main(){ return addx(3,ret3()); }"
assert 15 "int add(int a,int b,int c,int d,int e) { return a+b+c+d+e;} int main(){ return add(1,2,3,4,5); }"
assert 7 "int main(){int a=6;if(1>0){int a = 4,b=3;return a+b;} return a;}"
assert 6 "int ret2(int a,int b) { return a + b;} int main() { int c = 3;return c + ret2(1,2); }"
assert 7 "int ret2(int a,int b) { return a + b;} int main() { int a = 1,b = 2; return a + b + ret2(1,ret2(1,2)); }"
assert 2 "int ret(int a) { if(a == 0) return 0; else return 1 + ret(a-1); } int main() { return ret(2); }"
assert 10 "int i,j;int ret() { i = 3;j = 4;return i+j;} int main() { int i = 1,j = 2; return i + j + ret(); }"
assert 4 "int i,j; int ret() { i = 2;j = 4; if(i > j) return i;else return j;} int main() { return ret(); }"
assert 4 "int main() { int i = 4; return *(&i); }"
assert 3 "int i;int main() { i = 3;return *(&i); }"
assert 9 "int main() { int i = 4,*p = &i;*p = 7; return *p + 2; }"
assert 4 "int a;int main() { a = 1;int *p = &a; *p = 4; return *p; }"
assert 6 "int a;int main() { int a = 1,*p = &a; *p = 4; return a + 2; }"
assert 4 "int main() { int i = 4; int *p = &i; int **q = &p; return **q; }"
assert 7 "int *ret() { int i = 3; return &i; } int main() { int i = 4; int *p = ret(); return i + *p; }"
assert 14 "int main() { int arr[2] = {1,2};arr[0] = 12;return arr[0] + arr[1];}"
assert 1 "int main() { int arr[2] = {1,2},i; i = arr[0]; return i;}"
assert 12 "int arr[2];int main() { arr[0] = 12;return arr[0];}"
assert 12 "int arr[2];int main() { int *p = arr;*p = 12;return arr[0];}"
assert 12 "int main() { int arr[2] = {1,2},*p = arr;*p = 12;return arr[0];}"
assert 12 "int main() { int arr[2] = {1,2+1},*p = &arr[1];*p = 12;return arr[1];}"
assert 5 "int ret5() { return 5;} int main() { int arr[1];arr[0] = ret5(); return arr[0];}"
assert 5 "int ret5(int *arr) { *arr = 5; return *arr; } int main() { int arr[2];return ret5(&arr[1]);}"
assert 3 "int main() { int i = 3,*arr[1] = {&i}; return *arr[0]; }"
assert 3 "int main() { int arr[2] = {1,3};return *(arr+1); }"
assert 3 "int main() { int arr[2] = {1,2},*p = arr;*(p+1) = 3;return arr[1]; }"
assert 3 "int main() { int arr[2] = {1,2},*p = arr,*q = p+1;*q = 3; return arr[1];}"
assert 3 "int main() { int arr[2] = {1,2},*p = arr+1;*p = 3; return p[0];}"
assert 3 "int main() { int arr[2] = {1,2},*p = arr+1;p = p-1; *p = 3;return arr[0];}"
assert 3 "int main() { int arr[2] = {1,2},*p = arr+1;arr[1] = 3;return *p;}"
assert 3 "int arr[2];int main() { int *p = arr;*p = 3;return arr[0];}"
assert 3 "int arr[2];int main() { int *p = arr+1;*p = 3;return arr[1];}"
assert 1 "int main() { char c = 1;return c;}"
assert 255 "int main() { char c = -1;return c;}"
assert 2 "int main() { char a = 1,b = 1;return a + b;}"
assert 2 "int main() { char a[3] = {1,2,3};return a[1];}"
assert 98 "int main() { char *s = \"abc\";return s[1];}"
assert 98 "int main() { char *s = \"abc\",*p = s;return p[1];}"
assert 98 "int test(char *s) { s[0] = 98;} int main() { char *s = \"bbb\"; test(s);return s[0];}"
assert 3 "int main() { int i = 0; while(i < 3) i = i+1;return i;}"
assert 10 "int main() { int arr[3] = {2,3,5},i = 0,total = 0;while(i < 3){ total = total + arr[i]; i = i + 1;} return total; }"
assert 10 "int main() { int arr[3] = {2,3,5},i = 0,total = 0,*p = arr;while(i < 3){ total = total + *p; p = p + 1;i=i+1;} return total; }"
assert 10 "int main() { int sum = 0;for(int i = 0; i < 10; i = i + 1) sum = sum + 1;return sum;}"
assert 10 "int main() { int sum = 0,arr[3] = {2,3,5};for(int i = 0; i < 3; i = i + 1) sum = sum + arr[i];return sum;}"
assert 10 "int main() { int sum = 0,i = 0,arr[3] = {2,3,5};for(; i < 3; i = i + 1) sum = sum + arr[i];return sum;}"
assert 10 "int main() { int sum = 0,i = 0,arr[3] = {2,3,5};for(; i < 3;){ sum = sum + arr[i]; i = i + 1;}return sum;}"
echo "OK"
afterexit
